server:
  port: 9006
spring:
  application:
    name: tensquare‐spit #指定服务名
  data:
    mongodb:
      host: 47.102.156.57
      database: spitdb
  redis:
    host: 47.102.156.57
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true